# Generated by Django 4.0.6 on 2022-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(to='donate_app.category')),
            ],
        ),
    ]
