# Generated by Django 4.0.6 on 2022-07-31 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_app', '0002_donation_pick_up_date_donation_pick_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(default=datetime.date(2022, 7, 31)),
        ),
    ]
